### ISSUE TITLE
错误信息：UnicodeEncodeError: 'latin-1' codec can't encode characters in position 8-13: ordinal not in range(256)

### ISSUE THREAD

**Issue by zhc637** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#1]
解决:使用下列命令修改系统语言为zh-utf8
dpkg-reconfigure locales

**Comment by TcDhlPro** [comment]
> 解决:使用下列命令修改系统语言为zh-utf8 dpkg-reconfigure locales

好的, 不是什么严重问题, 日后会优化掉

**Comment by TcDhlPro** [comment]
关于Linux系统语言: 英文/中文
英文状态下在运行安装程序时依旧会出现这个问题, 直接使用`dpkg-reconfigure locales`命令切换成`zh-utf8`
