### ISSUE TITLE
0.8.6出现无法读取未定义的地址的提示，进不去网络管理

### ISSUE THREAD

**Issue by jenarlion** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#2]
大佬，你好
我在使用的时候，win7下用的是1.6.6，0.8.6出现无法读取未定义的地址的英文提示，也进不去网络管理
但是我使用0.8.7的时候就没问题可以使用，但是就是你提到的最后一列网络地址出现很多的问题

**Comment by TcDhlPro** [comment]
截个图看看

**Comment by jenarlion** [comment]
我把0.8.7卸载了 再安装0.8.6复现不了了，算了 ，麻烦了，谢谢



叶贸中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 下午3:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui] 0.8.6出现无法读取未定义的地址的提示，进不去网络管理 (Issue #2)





 
截个图看看

**Comment by TcDhlPro** [comment]
> 我把0.8.7卸载了 再安装0.8.6复现不了了，算了 ，麻烦了，谢谢 叶贸中 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui" ***@***.***&gt;; 发送时间:&nbsp;2023年1月13日(星期五) 下午3:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui] 0.8.6出现无法读取未定义的地址的提示，进不去网络管理 (Issue #2) 截个图看看 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你是在服务器上有0.8.7的情况下, 安装了我这个0.8.6么?
我这版本的0.8.6是跟着官方版本来的, 其中的一些文件的代码跟这个(0.8.7)的代码会有点不同, 官方前段时间更新过

**Comment by TcDhlPro** [comment]
网上的这个0.8.7应该是他们编译的时候, 改了下版本号, 实际应该还是旧版的0.8.6
官方这边确实有(0.8.7)这个版本, 但没有公开发布, 所以我才会强调了一下, 目前最新版依旧是0.8.6

**Comment by TcDhlPro** [comment]
如果你刚才重新安装了我这版本, 功能使用也正常的话, 建议下次保持环境干净再安装
