### ISSUE TITLE
救救孩子吧，死活连不上，后台不显示新加入设备

### ISSUE THREAD

**Issue by batxxc** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#4]
所有配置都正确也更换了Planet文件
![image](https://user-images.githubusercontent.com/130862282/232276718-eba5a089-313c-4d60-82fe-5bf4096772e3.png)

![image](https://user-images.githubusercontent.com/130862282/232276853-afaf948e-830b-4b23-b1d9-35499a2ce3f6.png)

死活连不上，后台没任何反应，

在阿里云后台我也开放了端口

**Comment by TcDhlPro** [comment]
你服务器上打个命令`zerotier-cli listpeers`看看

**Comment by TcDhlPro** [comment]
你Windows替换Planet文件后, 还得在`服务`中重启下ZeroTier的服务

**Comment by batxxc** [comment]
> 你Windows替换Planet文件后，还得在`服务`中重新启动下ZeroTier的服务

 你说的这种我肯定都试过，zerotier来回安装不下三次，包括替换文件，重启服务这些内容我肯定也是做了的

**Comment by TcDhlPro** [comment]
> > 你Windows替换Planet文件后，还得在`服务`中重新启动下ZeroTier的服务
> 
> 你说的这种我肯定都试过，zerotier来回安装不下三次，包括替换文件，重启服务这些内容我肯定也是做了的

神奇

**Comment by TcDhlPro** [comment]
你直接在服务器, 用命令查看`zerotier-cli listpeers`, 看下能不能打印出来你电脑的IP,  如果没有, 那就不是这个控制器的事

**Comment by TcDhlPro** [comment]
> 所有配置都正确也更换了Planet文件 ![image](https://user-images.githubusercontent.com/130862282/232276718-eba5a089-313c-4d60-82fe-5bf4096772e3.png)
> 
> ![image](https://user-images.githubusercontent.com/130862282/232276853-afaf948e-830b-4b23-b1d9-35499a2ce3f6.png)
> 
> 死活连不上，后台没任何反应，
> 
> 在阿里云后台我也开放了端口

如果你的问题跟他遇到的有点类似, 那也可以参考下
[Gitee Issues](https://gitee.com/dhlgits/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui/issues/I6Z7KQ)

**Comment by TcDhlPro** [comment]
你的问题应该也是没有在安全组中, 放行ZeroTier运行端口的UDP协议, 放行后就可以正常通讯到
