### ISSUE TITLE
  可以增加一个安装在域名的方法吗？

### ISSUE THREAD

**Issue by batxxc** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#5]
家里有台服务器有公网IP，但是弹性IP没法固定， 所以只能映射到域名上， 有没有啥方法可以安装？

**Comment by TcDhlPro** [comment]
官方也没有采取域名解析的方式, 应该是不支持你说的这种方式的, 建议弄一台固定IP的服务器
