### ISSUE TITLE
可以把planet弄成一个链接吗

### ISSUE THREAD

**Issue by wxc807** [TcDhlPro/ZeroTierOne-SelfHostingNetworkControllers-ZtnCui#6]
大佬你好，我是一个linux小白，
我想请教如何把planet文件设置成一个链接
如：https://1.1.1.1:4000/planet可以直接下载planet文件

我以为类似Windows  IIS一样，在把planet放在web目录就可以了，谁成想，找了好久找不到web目录
希望您在闲暇之余回复下。
1：key networks是通过什么方式架设web服务的（我在key networks官网看是，有用到node.js，百度翻译看的。。。。）
2：planet外链，可以自行解决吗？
如果不行，也没关系，最主要想学习，了解一下，解决一下我的困惑。

**Comment by TcDhlPro** [comment]
最初是有想过在控制器的后台页面中, 加一个可下载文件的地方, 但实际不好操作
自己弄外链的话你可以放网盘或者通过Nginx,或者通过1panel, 宝塔这种面板来实现
